### ISSUE TITLE
Support JRuby

### ISSUE THREAD

**Issue by jmoody** [calabash/calabash#21]
We support JRuby?
- [ ] Update .travis.yml
- [ ] Update 'we support' documentation
- [ ] Can we require MRI ruby 2.0 and JRuby 1.9?
